// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('fibonaccai', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('fibonacci', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    {
      const element = await driver.findElement(By.linkText("Factorial"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".p-ink-active"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.linkText("Factorial")).click()
    await driver.findElement(By.id("firstname1")).click()
    await driver.findElement(By.id("firstname1")).sendKeys("23")
    {
      const element = await driver.findElement(By.css(".p-button-label:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".p-ink-active"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".formgroup-inline > .p-button")).click()
    await driver.close()
  })
})